<ReportScreen>
    MDBoxLayout:
        orientation: "vertical"
        padding: "10dp"
        spacing: "8dp"

        MDLabel:
            text: "Reports Dashboard"
            halign: "center"
            bold: True
            size_hint_y: None
            height: "35dp"

        MDBoxLayout:
            size_hint_y: None
            height: "45dp"
            spacing: "5dp"

            MDRaisedButton:
                text: "ALL"
                on_release:
                    root.show_all_report()

            MDRaisedButton:
                text: "DATE"
                on_release:
                    root.show_date_report()

            MDRaisedButton:
                text: "MONTH"
                on_release:
                    root.show_month_report()

            MDRaisedButton:
                text: "RANGE"
                on_release:
                    root.show_range_report()

        MDGridLayout:
            cols: 2
            spacing: "5dp"
            size_hint_y: None
            height: "110dp"

            MDCard:
                size_hint_y: None
                height: "50dp"
                radius: [15]

                MDBoxLayout:
                    orientation: "vertical"

                    MDLabel:
                        text: "Income"
                        halign: "center"
                        size_hint_y: None
                        height: "15dp"

                    MDLabel:
                        id: income_label
                        text: "₹ 0"
                        halign: "center"
                        size_hint_y: None
                        height: "20dp"
                        theme_text_color: "Custom"
                        text_color: 0.2, 0.8, 0.2, 1

            MDCard:
                size_hint_y: None
                height: "50dp"
                radius: [15]

                MDBoxLayout:
                    orientation: "vertical"

                    MDLabel:
                        text: "Pending"
                        halign: "center"
                        size_hint_y: None
                        height: "15dp"
                      

                    MDLabel:
                        id: pending_label
                        text: "₹ 0"
                        halign: "center"
                        size_hint_y: None
                        height: "20dp"
                        theme_text_color: "Custom"
                        text_color: 1, 0.6, 0, 1

            MDCard:
                size_hint_y: None
                height: "50dp"
                radius: [15]

                MDBoxLayout:
                    orientation: "vertical"

                    MDLabel:
                        text: "Expense"
                        halign: "center"
                        size_hint_y: None
                        height: "15dp"
                      

                    MDLabel:
                        id: expense_label
                        text: "₹ 0"
                        halign: "center"
                        size_hint_y: None
                        height: "20dp"
                        theme_text_color: "Custom"
                        text_color: 1, 0.3, 0.3, 1

            MDCard:
                size_hint_y: None
                height: "50dp"
                radius: [15]

                MDBoxLayout:
                    orientation: "vertical"

                    MDLabel:
                        text: "Net Profit"
                        halign: "center"
                        size_hint_y: None
                        height: "15dp"
                      

                    MDLabel:
                        id: profit_label
                        text: "₹ 0"
                        halign: "center"
                        size_hint_y: None
                        height: "20dp"
                        theme_text_color: "Custom"
                        text_color: 0.3, 0.7, 1, 1

        MDLabel:
            text: "Pending Customers List"
            halign: "center"
            bold: True
            size_hint_y: None
            height: "30dp"

        ScrollView:

            MDGridLayout:
                id: pending_container
                cols: 1
                spacing: "5dp"
                padding: "5dp"
                size_hint_y: None
                height: self.minimum_height

        MDCard:
            size_hint_y: None
            height: "55dp"

            MDGridLayout:
                cols: 5
                spacing: "3dp"

                MDRaisedButton:
                    text: "Home"
                    on_release:
                        app.root.current = "home"

                MDRaisedButton:
                    text: "Customer"
                    on_release:
                        app.root.current = "customer_ledger"

                MDRaisedButton:
                    text: "Expenses"
                    on_release:
                        app.root.current = "expense"

                MDRaisedButton:
                    text: "Report"
                    md_bg_color: "#424242"

                MDRaisedButton:
                    text: "Settings"
                    on_release:
                        app.root.current = "settings"